- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/OnboardedProductResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInfoResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionRoleResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/OnboardedProductMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInfoMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInstitutionRoleMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInfoService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInfoServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/test/it.pagopa.selfcare.user/service/UserInfoServiceTest.java
- apps/user-ms/src/test/it.pagopa.selfcare.user/service/UserInstitutionServiceTest.java
Added services for UserInfo and UserInstitution
> [SELC-3724] feat: Added services for UserInfo and UserInstitution

- .github/labeler.yml
- .github/workflows/check_pr.yml
- .github/workflows/code_review_libs.yml
- .github/workflows/code_review_ms.yml
added yml for check_pr and code_review
added required review for pr and code
> [SELC-3810] Feat: added yml for check_pr and code_review

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserProductResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/OnboardedProductMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it.pagopa.selfcare.user/service/UserServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/InstitutionControllerTest.java
- Exposed API into InstitutionController
- Created logic into UserService to retrieve user's info from pdv rest client
- Created unit tests for both layers
> [SELC-3898] feat: Added API that replicates logic of /institutions/{institutionId}/users of ms-core

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/conf/JacksonConfiguration.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/conf/UserMsConfig.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/OnboardedProductResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/entity/OnboardedProduct.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/QueryUtils.java
- apps/user-ms/src/main/resources/application.properties
- add config for products libs
- fix query operation and Utils,
- change date type in model to String>
- We couldn't use Product libs without configuration
- Common method to execute query for find and update didn't work correctly
> [SELC-3890] Fix: added config for products libs, fixed query operation and Utils, change date type in model to String

- infra/mongo/.terraform.lock.hcl
- infra/mongo/env/dev/backend.ini
- infra/mongo/env/dev/backend.tfvars
- infra/mongo/env/dev/terraform.tfvars
- infra/mongo/env/uat/backend.ini
- infra/mongo/env/uat/backend.tfvars
- infra/mongo/env/uat/terraform.tfvars
- infra/mongo/locals.tf
- infra/mongo/main.tf
- infra/mongo/mongo_db.tf
- infra/mongo/outputs.tf
- infra/mongo/variables.tf
- Added base files for infra  for db mongo selcUser
On new project infra files is included in repo.
> [SELC-3811] Feat: Added infra directory for mongodb

- apps/pom.xml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
- apps/user-ms/src/test/java/it.pagopa.selfcare.user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it.pagopa.selfcare.user/service/UserServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- Added API to delete userInstitution product
This API will substitute old API, with the same interface, in ms-core
Tested locally with dev mode.
The API was called from Postman, and the update of the product status was verified.
> [SELC-3902] Feat: added API to delete userInstitution product

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Added new api to retrieve the usersInstitutions given a list of userIds
Necessity to retrieve a list of users by their ids
> [SELC-3931] feat: add retrieveUsersByIds

- apps/user-core-migration/migration.py
- apps/user-core-migration/query.py
- added institution parent description in model to migrate
We need to persist in new user models parentDescription field
> [SELC-3727] Fix: fix on migration script to add institution parent description

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Added api to retrieve filtered paginated users
it is necessary to expose this api because it must be used by bff.
> [SELC-4907] Feat: Added api to retrieve filtered paginated users

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/entity/UserInstitution.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- Added institutionRootName in UserInstitution model and response
The field is required by those who use the API and is part of that model.
> [SELC-4112] Feat: Added institutionRootName in UserInstitution model and response

- apps/user-cdc/pom.xml
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/config/TelemetryClientConfig.java
- apps/user-cdc/src/main/resources/application.properties
Added the sending of custom events using the telemetry client in the event of both successful and unsuccessful update operations, along with customized metrics based on the specific cases.
In the context of the automatic update of the UserInfo collection based on update and insert events in the UserInstitution collection triggered and processed by the user-cdc module, it is necessary to implement a mechanism for tracking any errors during these update operations. This is crucial as data inconsistency in this collection could lead to functional issues. Therefore, the decision has been made to utilize events and metrics on Application Insights to trigger alarms in case an update is not successfully completed.
> [SELC-3730] Feat: added appInsights track event for userInfo update

- .github/workflows/call_code_review.yml
- .github/workflows/pr_cdc.yml
- added yaml for user-cdc pr code review
At the moment, we only have code review pipelines for the user microservice. It's necessary to add them also for the user CDC module.
> [SELC-4074] Feat: added code review pipeline for user-cdc

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/InstitutionProducts.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/entity/UserInstitution.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/entity/UserInstitutionRole.java
Add idMail field to User related resources returned by api
New email seraching method will be implemented, the previous search by institutionId will be discarded for the new search method using the unique id assigned to the mail given durign onboarding procedure
> [SELC-4188] feat: add idMail field to resources

- .github/workflows/call_release_cdc.yml
- .github/workflows/call_release_infra.yml
- .github/workflows/call_release_ms.yml
- .github/workflows/release_cdc.yml
- .github/workflows/release_container_apps_infra.yml
- .github/workflows/release_container_apps_pnpg_infra.yml
- .github/workflows/release_mongo_infra.yml
- .github/workflows/release_mongo_pnpg_infra.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_pnpg_ms.yml
- .github/workflows/release_user_sdk.yml
- apps/user-cdc/Dockerfile
Added github action for user-ms and user-cdc release
> [SELC-3924] feat: added github action for user-ms and user-cdc release

- apps/user-ms/pom.xml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/conf/AwsSesConfig.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/AwsMailServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/MailService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/MailServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/AwsMailServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/MailServiceImplTest.java
-  added mailService interface
-  added mailServiceImpl with quarkusMailer client
-  added awsMailServiceImpl with aws ses client
For sending emails to users, it has been decided to no longer use the notification manager microservice but to handle the email sending directly on the selfcare-user, in agreement with the new selfcare-onboarding microservice. Therefore, it is necessary to create the interfaces and clients to allow the sending of emails both via Quarkus mail and via AWS SES depending on the value of an environment variable.
> [SELC-4195] Feat: added mailService with 2 impl (quarkus mailer and AWS ses)

- infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/prod/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
Update terraform variables for pnpg and each env
> [SELC-3924] fix: Update terraform variables for pnpg and each env

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/CertifiableFieldResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserDetailResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/WorkContactResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Added new api to retrieve all the information of a user given its ID from userRegistry without any logic
Dashboard will not be calling pdv directly, instead it will call ms-user to retrieve the user's information, including workContacts
Tested locally by launching the application
> [SELC-4334] feat: Added api getUserDetailsById

- apps/pom.xml
Updated pom dependency versions
> [resolve] Update user-ms-pom dependencies with onboarding sdk

- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/AwsMailServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Fixed errors in junit tests
On branch main, some assertions were failing. It was necessary to fix these errors.
> [SELC-441] feat: Solved errors in junit tests

- apps/user-ms/pom.xml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/CollectionUtil.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserDataResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- Added new Api to retrieve filtered userData
It is necessary to expose an API to retrieve user data to be returned to the frontend for the user section. The data to be returned is the concatenation of the user's personal data taken from PDV and the user's product data taken from the database.
> [SELC-4203] Feat: added Api to retrieve filtered userData

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- Refactor API to retrieve user institution list from UserInfo collection
This APi is used to retrieve user's institution List after login in dahsboard FE. So we need to return correct response to simplify bff logic
> [SELC-4517] Fix: Refactor API to retrieve user institution list from UserInfo collection

- apps/user-ms/pom.xml
- Removed dependency for Kafka
- Added dependency **org.eclipse.microprofile.metrics** necessary for aws sdk
I have run the command **mvn clean install** locally and no tests failed.
> [SELC-4540] feat: Removed dependency for Kafka

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/OnboardedProductMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- Added API to addUserRole
It is necessary to expose a new API on User for assigning a new role to a user as the existing user creation one requires different input parameters.
> [SELC-4539] Feat: Added API to addUserRole

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/resources/application.properties
Added quarkus.smallrye-openapi.store-schema-directory properties that indicate where store openapi docs
> chore: build openapi docs when package maven phase

- infra/container_apps/user-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/prod/terraform.tfvars
- infra/container_apps/user-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-cdc/variables.tf
- infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/main.tf
- infra/container_apps/user-ms/variables.tf
Migration to Container App DEV supporting a workload profile
> chore: Workload profiles migration DEV

- infra/container_apps/user-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-cdc/variables.tf
Remove workload_profile_name variables because is default on terraform module
Change PNPG dns suffix url
Migration to new Container Apps environment with Workload profile
> chore: Workload profiles migration PNPG

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/CertifiableFieldResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserMapperTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
fixed incorrect Mapping of userCertified fileds
> [SELC-4644] fix: user fileds certification mapping issue

- infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/main.tf
- infra/container_apps/user-ms/variables.tf
Remove workload_profile_name
Migration to new Container Apps Env for PNPG
> chore: remove workload_profile_name

- .github/workflows/release_pnpg_cdc.yml
> chore: Release pipeline User-Cdc PNPG

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/TemplateMailConstant.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/CreateUserDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/notification/PrepareNotificationData.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapperTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Added integration with Kafka and email sending for user creation api.
The ms-core APIs that the ms-user APIs take their cue from had integration with kafka and mail forwarding. So we brought back the same features
local env
> [SELC-4551] feat: Added integration with Kafka and email sending for user creation api

- infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
Added variables for rest client kafka for pnpg
> [SELC-4663] feat: Added variables for rest client kafka for pnpg

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/UpdateUserRequest.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
Fixed UpdateUser API
UpdateUserAPI doesn't persist correct IdMail on UserInstitution
local env
> [SELC-4666] Fix: Refactor UpdateUser API

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/UpdateUserRequest.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
- fixed mapper for user certified field
we need to exclude from mapper certifiedField if null
> [SELC-4666] Fix: fixed mapper for user certified field

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapperTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Fixed updateUserInstitutionByUserId method to create new entity when userInstitution not found
During the onboarding completion phase, we need to persist the user on the 'user institution' collection even if there isn't already a document in that collection with that userId and InstitutionId.
> [SELC-4668] Fix: updateUserInstitutionByUserId method to create new entity when userInstitution not found

- infra/container_apps/user-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/prod/terraform.tfvars
- infra/container_apps/user-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/uat/terraform.tfvars
- infra/container_apps/user-cdc/locals.tf
- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-cdc/variables.tf
- infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/prod/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
- infra/container_apps/user-ms/locals.tf
- infra/container_apps/user-ms/main.tf
- infra/container_apps/user-ms/variables.tf
* Container App env name must be specified
* workload_profile null for dev and prod 
Container App env could have a different configuration among dev or uat or prod.
> chore: Migration to Container App module with name and workload_profile empty

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
Added filter to remove products from userinstitution records when state isn't allowed, in retrieveUsers API.
The fix is mandatory and is a filter on the status of products after the query results are retrieved, because currently the API only performs a filter on the query, but because of the structure of the UserInstitution collection if a user has multiple products both those with the desired status and those with the status to be discarded are returned.
> [SELC-4683] fix: added filter to remove products from userinstitution records when state isn't allowed

- infra/container_apps/user-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/prod/terraform.tfvars
- infra/container_apps/user-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/uat/terraform.tfvars
- infra/container_apps/user-cdc/locals.tf
- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-cdc/variables.tf
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
- infra/container_apps/user-ms/locals.tf
- infra/container_apps/user-ms/main.tf
- infra/container_apps/user-ms/variables.tf
Using terraform ca module with suffix
Change cae url uat
Migration uat env with -001 suffix
> chore: Migration uat using terraform ca module with suffix

- apps/user-cdc/pom.xml
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-cdc/src/main/resources/application.properties
- infra/container_apps/user-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/dev/terraform.tfvars
* Using only one var for APPLICATIONINSIGHTS_CONNECTION_STRING
* Added quarkus-smallrye-health for health endpoint
> chore: Adding health endpoint to User-Cdc 

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/resources/application.properties
- infra/container_apps/user-ms/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/prod/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
Added USER_MS_EVENTHUB_USERS_ENABLED var that enable sending notification to eventhub
PNPG use case does not need to send notifications to eventhub
> [SELC-4703] bugfix: sending notification to eventhub optionally

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserInfo.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserInstitution.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserInstitutionRole.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/mapper/UserMapper.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
- apps/user-cdc/src/main/resources/application.properties
-  fixed update and create userInfo on userCDC
User CDC doesn't create or update userInfo collection correctly
local env
> [SELC-4705] Fix: fixed update and create userInfo on userCDC

- .github/workflows/create_release_branch.yml
> chore: Create release workflow

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
> fix update User product Status add checkTo existing product when create new User

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
-Fixed query to delete product in status ACTIVE
When we have to delete user product, If user has more productObject for the same productId with different status we need to update only the product with status ACTIVE
> [SELC-4684] Fix:  query to delete product in status ACTIVE

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/OnboardedProductMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
…
- fixed add Product role when productRole list has more than 1 elements
We could receive more than one user productRoles, so we have to add more onboarded product on userInstitution
> [SELC-4551] Fix: fixed add Product role when productRole list has more than 1 elements

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserInstitutionRole.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/mapper/UserMapper.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
> hotfix: rename status name in user-cdc

- infra/container_apps/user-cdc/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/uat/terraform.tfvars
> chore: increase cdc resource for dev and uat

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- Added check for null workcontacts map
We receive a nullpointer when pdv returns null workcontact map
> Fix: Added check for null workcontacts map

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/SearchUserDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- fix for null userMailUuid when try to retrieve workContact
When we try to retrieve email for workContact we have to check if key value is null before try to get null key value on map.
> Fix: fix for null userMailUuid when try to retrieve workContact

- .github/workflows/pr_ms.yml
- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-ms/main.tf
- infra/container_apps/user-ms/mongo_db.tf
Create mongo index userId-institutionId
> chore: create index userId-institutionId

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
> hotfix: set logged user empty when not found and sending mail

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Added mapping mail on GET /institutions/{id}/users
> [SELC-4759] fix: mapping mail from workContracts

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Throw exception when adding new role on product if already exists one
It's not permited to have more roles on the same product
> [SELC-4799] hotfix: avoid add role on product if already exists one

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
Filter status ACTIVE when return mail bu userId
> [SELC-4800] hotfix: filter status ACTIVE when retrieve mails

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
Added filter data after retrieve from db for productId,status,role and productRole
> [SELC-4849] hotfix: filter data after retrieve from db on GET /users

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/SearchUserDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/entity/filter/UserInstitutionFilter.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/util/UserUtilTest.java
- Added productRole as param in UpdateUserProductStatus API
When product has more than one productRole we have to filter on productRole to update userProduct status
> [SELC-4836] Fix: Added productRole as param in UpdateUserProductStatus API 

- apps/user-core-migration/migrate_institution_description.py
- apps/user-core-migration/query.py
- Added script for institutionDescription migration from selcMsCore.Institution to selcUser.userInstitutions
Some userInstitutions documents don't have institutionDescription so we have to migrate this field from institution collection of selcMsCore DB
> [SELC-4737] Feat: Added script for institutionDescription migration from selcMsCore.Institution to selcUser.userInstitutions

- .github/workflows/pr_cdc.yml
- .github/workflows/release_ms.yml
* Fix pr workflow removing actor param
* Added promote release step on release_ms workflow
> chore: added promote release step to release_ms workflow

- apps/user-core-migration/migration.py
- apps/user-core-migration/query.py
…d parametrized userId migration for userInfos
Removed userInstitutions migration code and added parameter for importing single user userInfo details
> [SELC-4804] feat: remove userInstitutions migration script and add userId parameter for userInfo migration

- apps/user-core-migration/migrate_institution_description.py
- apps/user-core-migration/query.py
- Added script for institutionDescription migration from selcOnboarding.Onboarding to selcMsCore.Institution
Some Institution documents don't have institutionDescription so we have to migrate this field from onboarding collection of selcOnboarding DB
> [SELC-4736] Feat: Added script for institutionDescription migration from selcOnboarding.Onboarding to selcMsCore.Institution

- apps/user-ms/pom.xml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/filter/CustomLoggingFilter.java
* Added **CustomLoggingFilter** class in the **it.pagopa.selfcare.user.filter** package.
* Implemented the filter method to log the HTTP method and endpoint of incoming requests.
Custom logging filter that logs the HTTP method and endpoint of incoming requests. The filter is implemented using **ResteasyReactiveContainerRequestFilter**.
> chore: Add CustomLoggingFilter to log incoming requests

- apps/user-core-migration/query.py
- apps/user-core-migration/retrieve_taxCode_from_institution.py
- Added script to persist fromTaxCode and toTaxCode in Delegations collection
We need to persist also taxcode for from and to institution in delegation collection, so we have to migrate these field from institution collection
> [SELC-4909] Feat: Added script to persist fromTaxCode and toTaxCode in Delegations collection

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- Refactor build data model for send mail to map correct role label
Currently, in the content of the email, we map the role not with the role label but with the code.
> [SELC-4932] Feat: Refactor build data model for send mail to map correct role label

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
- set institutionName, institutionRootParent and userMailUuid on UserInfo when updating UserInstitution
It has been tested by running locally user-cdc and modify mentioned fields on UserInstitution collection
> [SELC-4966] feat: update institutionName, institutionRootParent and userMailUuid on UserInfo

- apps/user-core-migration/migrate_institution_description.py
- apps/user-core-migration/query.py
This PR avoid to scan entire list of onboarding to find institution that has not description. It find only institution without description but that has one onboarding. It is used only for PNPG use case
> chore: refactor script migrate institution description using institution description not exist

- .github/workflows/swagger_detect_quarkus_ms.yml
Using a common GitHub Action designed to facilitate the detection of conflicts in Swagger documentation files
> ops: GitHub Action to detect breaking changes on Swagger

- apps/user-cdc/pom.xml
- Updated quarkus.platform.version to 3.11.0 for user-cdc
User-cdc was started locally, a modification was made to a product state on a userInstitution document, and the flow f was followed in debug mode. Finally, the correct update of the user in the userInfo collection was verified.
> [SELC-4998] Feat: Update quarkus.platform.version to 3.11.0 for user-cdc

- .github/workflows/call_code_review.yml
- .github/workflows/call_release_ms.yml
- .github/workflows/release_user_sdk.yml
- pom.xml
selfcare-onboarding reference to repository must be the same for selfcare
> ops: refactor selfcare-github repo name with selfcare-onboarding

- apps/user-ms/pom.xml
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/resources/application.properties
- Updated quarkus.platform.version to 3.11.0 for user-cdc
User-ms was started locally, and some API was tested
> [SELC-4997] Update quarkus.platform.version to 3.11.1 for user-ms

- apps/pom.xml
- apps/user-ms/pom.xml
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/OnboardedProductResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionRoleResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/entity/OnboardedProduct.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/notification/UserToNotify.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- updated common skd version to introduce new PartyRole ADMIN_EA
- added delegationId in UserInstitution Products
- aligned unit tests
- aligned open api
This change is related to new feature of Enti Aggregatori.
It was tested by running ms-user locally, calling createOrUpdateByUserId API and checking that field delegationId was persisted.
> [SELC-4977] feat: added delegationId in UserInstitution products and update sdk version to introduce ADMIN_EA PartyRole

- apps/user-group-ms/app/src/main/docs/openapi.json
- apps/user-group-ms/web/src/main/java/it/pagopa/selfcare/user_group/web/config/SwaggerConfig.java
- apps/user-group-ms/web/src/main/java/it/pagopa/selfcare/user_group/web/controller/UserGroupController.java
- apps/user-group-ms/web/src/main/java/it/pagopa/selfcare/user_group/web/controller/UserGroupV1Controller.java
- apps/user-group-ms/web/src/main/java/it/pagopa/selfcare/user_group/web/handler/UserGroupExceptionHandler.java
- apps/user-group-ms/web/src/test/java/it/pagopa/selfcare/user_group/web/controller/UserGroupV1ControllerTest.java
Added new controller that expose this endpoint, the legacy controller will be deprecated
This pull request addresses the inconsistency in the endpoint path for the user-group* microservice. Specifically, it modifies the existing **/user-group/v1* endpoint to **/v1/user-group** to align with the versioning standard used across all microservices in the selfcare platform.
> [SELC-5045] feat: Update Endpoint Path to Include Version for User-Group MS

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- add "support" tags to getUserInfo and getInstitutionUsers
- align openapi
Align tags for implementation of this [RFC](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/edit-v2/1084883169)
> [SELC-5054] chore: add "support" tags to getUserInfo and getInstitutionUsers

- apps/user-ms/Dockerfile
Fix for this [PR](https://github.com/pagopa/selfcare-user/pull/151)
> [SELC-4979] fix: Adding src WORKDIR on user-ms Dockerfile

- apps/user-group-ms/app/src/main/docs/openapi.json
- apps/user-group-ms/web/src/main/java/it/pagopa/selfcare/user_group/web/controller/UserGroupV1Controller.java
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- add support-pnpg tag to getInstitutionUsers
- add support-pnpg tag to getUserGroups
- align openapi
Align tags for implementation of this [RFC](https://pagopa.atlassian.net/wiki/spaces/SCP/pages/edit-v2/1084883169)
> [SELC-5092] chore: add support-pnpg tag to getInstitutionUsers and getUserGroups

- apps/user-ms/pom.xml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/conf/UserMsConfig.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
* Added logic to split the list of SC-User events into pages of a predefined size.
* Introduced configuration settings for page size and parallel processing limits.
* Added send metric SendEvents_* to appinsights in order to monitor how many events have been send
The primary goal of this update is to introduce pagination in the resending of SC-User events. By breaking down the list of events into smaller, manageable pages and sending them in parallel, we aim to avoid excessive memory consumption that can occur when handling large lists of events. This enhancement is essential for maintaining the efficiency and stability of the system, ensuring that resource utilization remains optimal during the event resending process.
> [SELC-5128] feat: Add Pagination for SC-User Event Resending

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/QueryUtils.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/TrackEventInput.java
- libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/UserUtilsTest.java
- test-coverage/pom.xml
* Adding TrackEventInput for tracking better events
* Adding pagination size as env variable
* Set concurrency to 1 with a delay of 5 seconds to avoid error 429 from PDV service. Here we have a rate limit of 60 req/sec
* Fix test coverage module adding user-libs
> [SELC-5128] refactor: Adding pagination size and limit in Send Event Metrics on sc-users

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/TrackEventInput.java
Added productRole measurement to track it on sending sc-users events
> feat: Added tracking product role on send events

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepositoryTest.java
Return optional empty state when products is null or empty. In this case, UseInfo record will be removed.
Products null or empty causes NoSuchElemen exception when retrieving  min status to set on UserInfo occurrence.
> [SELC-5225] bugfix: update UserInfo more reliable avoid error when products is null

- infra/container_apps/user-ms/role_action_mapping.json
- Added role_action_mapping.json
We need to manage user authorization with action, so we have to add a json to listing these action
> [SELC-5245] Feat: Added role_action_mapping.json

- infra/container_apps/user-cdc/env/uat/terraform.tfvars
- infra/container_apps/user-group-ms/.terraform.lock.hcl
- infra/container_apps/user-group-ms/env/uat/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
> chore: Move to Container App Env workload UAT

- libs/user-sdk-model/src/main/java/it.pagopa.selfcare.user.model/UserAction.java
- Added UserAction enum in user-sdk-model
We need to add enum for user's action, so that other ms can use enum instead of string
> [SELC-5251] Feat: Added UserAction enum in user-sdk-model

- infra/container_apps/user-cdc/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/prod/terraform.tfvars
- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-group-ms/env/prod/terraform.tfvars
- infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/prod/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
- infra/container_apps/user-ms/main.tf
- infra/container_apps/user-ms/mongo_db.tf
> chore: Move to Container App Env workload PROD

- apps/user-ms/src/main/resources/role_action_mapping.json
- Added Selc:ListActiveProducts for OPERATOR in role_action_mapping.json
> [SELC-5245] Feat: Added Selc:ListActiveProducts for OPERATOR in role_action_mapping.json

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
This endpoint must be exposed by Internal API
> chore: Add tag internal-v1 on users/:id/status update

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/exception/handler/ExceptionHandler.java
Replace custom ProblemError using which is defined in selfcare-common
Using different version could cause ambiguity when perform merge-openapi action
> chore: using ProblemError defined in selfcare-common

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
Allign response for merge openapi
> docs: set problem+json error response of update status

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
Allign response for merge openapi
> ops: Added swagger annotation Responses to Users/Instituions

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
* Added: Manual assignment of operationId for each API operation in the OpenAPI specification.
* Updated the OpenAPI generation process to ensure that operationId is explicitly set for all operations.
This PR addresses the issue where operationId was missing in the automatically generated OpenAPI documentation by Quarkus. By default, Quarkus does not automatically set the operationId in the OpenAPI specification. This can lead to difficulties when integrating with API clients or tools that rely on operationId for method names or routing.
> chore: Add operationId to OpenAPI Documentation

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepositoryTest.java
* New UserInfo Record Insertion:
The process of inserting a new UserInfo record has been optimized to require only a single persist operation.
If the logic enters the "new UserInfo" flow, any attempt to update an existing record will now fail, which allows the data to be reprocessed correctly. 
* Enhanced Record Update Mechanism:
The update logic has been modified to allow the addition of new entries to the institutions array within an existing UserInfo record without overwriting the entire record.
This change resolves the issue of parallel updates where previously, concurrent operations could lead to the overwriting of UserInfo records that were processed simultaneously. By appending to the institutions array instead of replacing it, the risk of data loss or corruption due to concurrent …
> [SELC-5265] fix: Enhancement of UserInfo Record Update Logic

- apps/pom.xml
Increase sdk product version 0.2.0
> [SELC-5520] feat: increase sdk product version to handle institutionContractMapping issue

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
This endpoint must be includes inside Support PNPG API
> [SELC-5572] feat: add tag support-pnpg to getUserInfoUsingGET

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/EventsController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserPermissionController.java
- apps/user-ms/src/main/resources/application.properties
* Added description Attribute: Each @operation annotation now includes a description attribute that provides a detailed explanation of the endpoint's functionality, complementing the existing summary.
* Using SmallRye auto-generate Operation Id
Enhancing your API endpoints with detailed summary and description attributes not only benefits external developers but also aids internal teams in maintaining and scaling the application. Well-documented APIs facilitate smoother integrations, reduce misunderstandings, and improve overall developer experience.
> chore: Added Auto-generation operationId and Swagger description on each endpoint

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/exception/handler/ExceptionHandler.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
* Add more details on ResourceNotFound exception
* switch to warn instead of error on not found and bad request exception
> chore: some improvement log messages on user service

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
This PR aims to fix a specific bug that happens when a users try to create another user using fiscalCode. First userRegistry not found the user by fiscalCode but it return Conflict in the next operation where it try to add the users
> hotfix: Added trim to fiscalCode when CreateUsersByFiscalCode

- infra/container_apps/user-cdc/main.tf
- infra/container_apps/user-group-ms/main.tf
- infra/container_apps/user-ms/main.tf
- infra/repository/main.tf
Fix of this https://pagopa.atlassian.net/wiki/spaces/DEVOPS/pages/463241875/Terraform+Troubleshooting+FAQs#%5CuD83E%5CuDD14-Problem%3A-Error-ensuring-Resource-Providers-are-registered.
> fix: Error ensuring Resource Providers are registered

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/InstitutionControllerTest.java
added external-pnpg tag on getUserInfo API
This API needs to be invoked by SEND services
> [SELC-5651] feat: added external-pnpg tag on getUserInfo API

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
Sometimes 404 occurs in spite of user is present on user registry. Retry request could fix the issues.
> feat: Add retry when find users on User Registry

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/CreateUserDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/OnboardedProductWithActions.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapper.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapperTest.java
- Removed PartyRole enum from controller request and response dto to remove them from openapi
The partyrole enums have been removed from the request and response DTOs, and consequently from the OpenAPI, as the addition of a new enum value was causing breaking changes during the OpenAPI review.
> [SELC-5594] Feat: Removed PartyRole enum from controller request and response dto to remove them from openapi

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/ActionMapRetriever.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/util/ActionMapRetrieverTest.java
- fixed filterProductAndAddActions method
- Added check on unit test to verify action list
The change of the role from PartyRole to String caused that when attempting to retrieve the list of actions from the action map using the role key, this did not return any results.
> [SELC-5594] fix filterProductAndAddActions method

- apps/pom.xml
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
This pull request introduces the usage of a new configuration option to associate Product Roles based on the InstitutionType. Usert-ms has an impact only on sending mail to retrieve the correct label of product role
> [SELC-5633] feat: retrieve product Role label from allRoleMappings

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
This PR aims to fix a case on PNPG domain where an user could have a workContracts populated with id but without mail references. In this case user-ms throw an NullPointerexception before this fix.
> [SELC-5752] fix: mapper toWorkContacts does not handle mail null

- apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/UserGroupCdcService.java
- apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/config/DateCodec.java
- apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/config/MongoConfig.java
- apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserGroupEntity.java
- apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/mapper/UserGroupNotificationMapper.java
- apps/user-group-cdc/src/main/resources/application.properties
- apps/user-group-cdc/src/test/java/it/pagopa/selfcare/user/event/service/UserGroupCdcServiceTest.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
- Added custom code to parse different format of date
In the userGroup database, the modifiedAt field contains two different formats: DateTime and Timestamp. Therefore, we need to read both formats without encountering exceptions.
> [SELC-5740] Fix: Added custom code to parse different format of date

- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/service/UserInstitutionCdcServiceTest.java
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/conf/DateCodec.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/conf/MongoConfig.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/EventsController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/OnboardedProductResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserNotificationResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/OnboardedProductWithActions.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/OnboardedProductMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserInstitutionMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/QueryUtils.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/conf/DateCodecTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/EventsControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/InstitutionControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/UserNotificationToSend.java
- libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/UserUtilsTest.java
- libs/user-sdk-model/src/main/java/it.pagopa.selfcare.user.model/OnboardedProduct.java
> [SELC-5827] Feat: added custom codec for user date

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
added tag internal-pnpg to POST /users API
With the tag we will expose the API on the internal pnpg api group
> [PNPG-239] feat: added tag internal-pnpg to POST /users API

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- Fix add user product Role to allowed multirole
- Currently, it was not possible to add a second productRole if there was already one active. For interoperability, this behavior is not acceptable since multi-role support is expected.
> [SELC-5856] Fix add user product Role to allowed multirole

- apps/user-group-cdc/src/main/resources/application.properties
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/resources/application.properties
added properties for eventhub in user-ms
> [SELC-5887] Fix: added properties for eventhub in user-ms

- infra/container_apps/user-cdc/env/uat/terraform.tfvars
> [SELC-5887] Fix: event hub base path UAT

- infra/container_apps/user-cdc/env/uat/terraform.tfvars
> [SELC-5887] Fix(cherry pick): event hub base path UAT 

- apps/user-group-cdc/src/main/resources/application.properties
- infra/container_apps/user-group-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-group-cdc/env/prod/terraform.tfvars
- infra/container_apps/user-group-cdc/env/uat/terraform.tfvars
> Fix: event hub base path and topic for user-group-cdc

- apps/user-group-cdc/src/main/resources/application.properties
- infra/container_apps/user-group-cdc/env/dev/terraform.tfvars
- infra/container_apps/user-group-cdc/env/prod/terraform.tfvars
- infra/container_apps/user-group-cdc/env/uat/terraform.tfvars
> [SELC-5887] Fix(cherry pick): fix event hub base path and topic for user-group-cdc

- apps/user-cdc/src/main/resources/application.properties
USER_CDC_SEND_EVENTS_WATCH_ENABLED has changed with true value enabling send events in pnpg use case
> Fix: set default value as false on USER_CDC_SEND_EVENTS_WATCH_ENABLED

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-cdc/src/main/resources/application.properties
- apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/UserGroupCdcService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/NotificationMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
- apps/user-ms/src/main/resources/application.properties
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
- apps/user-ms/src/test/resources/application.properties
- infra/container_apps/user-ms/env/dev/terraform.tfvars
- infra/container_apps/user-ms/env/prod/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
- libs/user-sdk-model/src/main/java/it.pagopa.selfcare.user.model/constants/EventsName.java
- Added send selfcare fd event after user mail update
We need to send 2 events (DELETE and ACTIVE) to selfcare-fd topic if user mail is changed.
> [SELC-5923] Feat: Added send selfcare fd event after user mail update

- .github/workflows/pr_validation.yml
- apps/pom.xml
This PR aims to handle a braking change introduced on product.json configuration resolved by onboarding-sdk 0.4.1 version
> Upgrade onboarding-sdk 0.4.1

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/exception/UserRoleAlreadyPresentException.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- Added API to createUser by userID from onboarding
The new API is necessary because, in the case of an already registered role, an exception should not be thrown; instead, the error should be logged and no operation should be performed.
> [SELC-5971] Feat: Added API to createUser by userID from onboarding

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserInstitution.java
- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/UserUtilsTest.java
- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/service/UserInstitutionCdcServiceTest.java
- apps/user-cdc/src/test/resources/application.properties
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
- libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/UserUtilsTest.java
- changed user-cdc business logic to eveluate if mail is changed
We need to check if user mail is changed before send events to selfcare-fd topic, to send correct Events
> [SELC-5981] Feat: changed user-cdc business logic to eveluate if mail is changed

- README.md
Description about how setup github credentials and Prerequisites to run java microservice
> docs: added Prerequisites and GH Credentials to README

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserDetailResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/openapi/user_registry.json
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserMapperTest.java
- update userRegistry openapi with mobilePhone field
- add mobilePhone field in getUserDetailsById API
- align mappers
- add and align unit tests
- align openapi
It was tested by invocking the mentioned api locally
> [SELC-6102] feat: add mobilePhone in getUserDetailsById API

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/CertificationEnum.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/CollectionUtil.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/CertifiableFieldResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/UpdateUserRequest.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
- apps/user-ms/src/main/openapi/user_registry.json
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserMapperTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/util/UserUtilTest.java
- Updated api updateUserRegistryAndSendNotification to allow updating the phone number in addition to the email.
It was necessary to modify this API to allow the addition and modification of the optional phone number.
> [SELC-6087] Feat: Updated api updateUserRegistryAndSendNotification

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/NotificationMapper.java
- cherrypick to align main branch after NotificationMapper hotfix
> [SELC-6121] fix: align main branch after NotificationMapper hotfix

- infra/container_apps/user-cdc/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-cdc/env/uat/terraform.tfvars
- infra/container_apps/user-group-cdc/env/uat/terraform.tfvars
- infra/container_apps/user-group-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-group-ms/env/uat/terraform.tfvars
- infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/user-ms/env/uat/terraform.tfvars
> [SELC-6134] Adding new scale rule for UAT

- apps/pom.xml
- apps/user-group-ms/pom.xml
- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/CreateUserDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/OnboardedProductResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionRoleResponse.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/OnboardedProductWithActions.java
- apps/user-ms/src/main/resources/role_action_mapping.json
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/util/ActionMapRetrieverTest.java
- apps/user-ms/src/test/resources/role_action_mapping_test.json
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/UserToNotify.java
- libs/user-sdk-model/pom.xml
- upgrade commons version to 2.5.6 to add ADMIN_EA_IO
- upgrade sdk version to 0.6.8 to add ADMIN_EA_IO
- set ADMIN_EA_IO allowed actions
- align unit test
- align openapis
> [SELC-6300] feat: add role ADMIN_EA_IO

- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/ActionMapRetriever.java
- apps/user-ms/src/main/resources/role_action_mapping.json
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/resources/role_action_mapping_test.json
- new permission actions management by role and product
- align unit tests
It was tested locally
> [SELC-6300] feat: new permission actions management by role and product

- apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/UserUtilsTest.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/util/UserUtilTest.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
- libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/UserUtilsTest.java
> [#SELC-6303] fix grouping on resend events and cdc process for sc_users

- apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/UserUtilsTest.java
- libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
- libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/UserUtilsTest.java
> Fix grouping Product for different product role and the same role

- infra/container_apps/user-cdc/env/uat/terraform.tfvars
-  enable USER_CDC_SEND_EVENTS_WATCH_ENABLED in UAT
This change is required to enable sending queue messsages in uat environment
> [SELC-6578] feat: enable USER_CDC_SEND_EVENTS_WATCH_ENABLED in UAT

- apps/user-ms/README.md
- apps/user-ms/src/test/resources/features/user.feature
- added scenario: Successfully update user product status from SUSPENDED to DELETED
- changed the user-registry-url environment variable in README file for cucumber test
Align cucumber test for the new feature of deleting a user with status SUSPENDED
It has been tested locally by running the new scenario alone and then re-running all the scenario
> [SELC-6962] feat: added cucumber test for deleting user with product status SUSPENDED, updated README for Cucumber tests

- .github/workflows/integration_tests_ms.yml
- apps/user-ms/README.md
- apps/user-ms/docker-compose.yml
- apps/user-ms/pom.xml
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/integration_test/CucumberSuite.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInfoServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/resources/application-test.properties
- apps/user-ms/src/test/resources/application.properties
- apps/user-ms/src/test/resources/blobStorageInit/initAzurite.sh
- apps/user-ms/src/test/resources/blobStorageInit/products.json
- pom.xml
- Added github workflow integration_tests_ms
- Added mock products.json (removing access to private repository)
- Forced language en_US with timezone GMT during tests
- Integrated testcontainers to load automatically the docker-compose.yml
- Cleanup of properties
- Removed unused dependency quarkus-test-mongodb
Start automatically all the dependencies when running the integration tests.
Execution of the integration tests when a new PR is opened.
- Local tests
> [SELC-7078] Running integration tests with github action, testcontainers and docker-compose

- apps/user-group-ms/Dockerfile
- apps/user-group-ms/pom.xml
- apps/user-ms/Dockerfile
- update server selfcare in Dockerfile
- update selfcare-common version in pom.xml
Fixes release workflow failures and enables successful builds by resolving cucumber-sdk dependency
> [SELC-7126] fix: added server selfcare in Dockerfile for user-group-ms and user-ms

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/SearchUserDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserPermissionServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/InstitutionControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserPermissionServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/resources/features/institution.feature
- apps/user-ms/src/test/resources/mock/user-registry-api.json
- add new API checkUser
- add unit tests
- add cucumebr tests
This new API is introduced to support the asynchronous user onboarding flow by enabling a check to determine whether a user already exists.
It was tested locally
> [SELC-7128] feat: add new API checkUser

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/OnboardedProductMapper.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- apps/user-ms/src/test/resources/features/user.feature
- modify POST users/{userId}/onboarding logic:
- when I add a user with role MANAGER but it's already present, then keep the existing user.
- when I add a user with role MANAGER but it's already present with another role, then delete the previous role and add it with MANAGER role with the previous state (ACTIVE or SUSPENDED)
- when I add a user with role different from MANAGER, if it's already present with status ACTIVE or SUSPENDED, then do not allow to add it again.
- align unit tests
- add cucumber tests
This change permits to avoid duplication of users during the asynchronous user onboarding flow.
It was tested locally, by unit tests and cucumber tests.
> [SELC-7130] feat: modify POST users/{userId}/onboarding

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/TemplateMailConstant.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/SendEmailOtpDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
> [#SELC-7067] Add Send OTP mail endpoint

- apps/user-ms/src/main/docs/openapi.json
- apps/user-ms/src/main/docs/openapi.yaml
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/SendMailDto.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/notification/PrepareNotificationData.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
- apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
- apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
- add userRequestUid in request body to get user request name and surname
- align unit tests
This change resolves an issue affecting the correct population of 'user' and 'surname' placeholders in the onboarding request initiated by the user.
It was tested locally
> [SELC-7166] fix: send mail to user for onboarding request

- apps/user-ms/src/test/resources/application-test.properties
- Update user registry mock key
Change user registry mock api key
> Change user registry mock key

- infra/container_apps/user-ms/mongo_db.tf
> [SELC-7586] Added index institutionId to userInstitution collection

- infra/container_apps/user-group-ms/mongo_db.tf
- Added index to field "name" in UserGroups collection
Solve a 502 Bad Gateway when the user try to order by name.
> [SELC-7600] Added index to field "name" in UserGroups collection

- apps/pom.xml
- update onboarding sdk version
This change is intended to handle the new institution types SCEC and PRV_PF
> [SELC-7756] feat: update onboarding sdk version
