pagopa/selfcare-user

apps/user-cdc/README.md
infra/.container_apps/user-cdc/.terraform.lock.hcl
infra/.container_apps/user-cdc/container_app.tf
infra/.container_apps/user-cdc/env/dev/backend.ini
infra/.container_apps/user-cdc/env/dev/backend.tfvars
infra/.container_apps/user-cdc/env/dev/terraform.tfvars
infra/.container_apps/user-cdc/env/prod/backend.ini
infra/.container_apps/user-cdc/env/prod/backend.tfvars
infra/.container_apps/user-cdc/env/prod/terraform.tfvars
infra/.container_apps/user-cdc/env/uat/backend.ini
infra/.container_apps/user-cdc/env/uat/backend.tfvars
infra/.container_apps/user-cdc/env/uat/terraform.tfvars
infra/.container_apps/user-cdc/locals.tf
infra/.container_apps/user-cdc/main.tf
infra/.container_apps/user-cdc/outputs.tf
infra/.container_apps/user-cdc/terraform.sh
infra/.container_apps/user-cdc/variables.tf

- added infra files for user-cdc
- we need to add infrastructure files for new user-cdc module

[SELC-3811] Feat: added infra files for user-cdc

---

apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java

…titutionId
Refactor logic on retrieve user email based on userMailUuid instead of institutionId on two apis:
- users/emails
- users/{id}
New way of persisting user informations will be adopted on pdv, especially for what regards workContacts, as per now the workContacts is a map having the institutionId as key and the email as value. With the new method every mail will have a unique identifier generated when the user is added durign an onboarding.
The logic on upstram microservice has to be updated to retrieve the mail based on this unique identifier instead of the institutionId
Runned application locally and verified the correct retrieval of the email

[SELC-4185] feat: refactor logic on retrieve user email based on userMailUuid instead of institutionId

---

apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java

Added products, status, roles, productRoles filters to remove products from userinstitution records retrieved
The fix is mandatory it allows to filter on products, status, roles, productRoles of products after the query results are retrieved, because currently the API only performs a filter on the query, but because of the structure of the UserInstitution collection if a user has multiple products both those who pass the filters and those who don't pass the filters are returned.
local env

[SELC-4683] fix: added filters to remove products from userinstitution records

---

apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/SearchUserDto.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/util/UserUtils.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java

* NotBlank annotation write wrong open api with pattern \S
* Fix return 500 in case of 404 pdv

[SELC-4706] fix: added NotNull on fiscalCode SearchUserDto

---

apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/CdcLifecycle.java
apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java

* Remove resume at startOperationTime
* Added resume after last token
* Saving last token on azure table
attempt resuming notifications starting after the operation specified in the resume token.
Each change stream event document includes a resume token as the _id field. Pass the entire _id field of the change event document that represents the operation you want to resume after.

feat: restart cdc after resume token at startup

---

apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserNotificationServiceImplTest.java

- Fixed constructTemplate for mail when institutionDescription is null
During the creation of the email for the user, we might have the institution description equal to null. This field in the data model should not be null but an empty string.

fix constructTemplate for mail when institutionDescription is null

---

apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/CdcLifecycle.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java

Update workContract on userRegistry we must create an empty map with only key that we want persist
Update pdv brokes when user has a lot of mail and we try to pass to bdoy entire workContracts. Passing just one key, pdv will add this key inside workContracts.

[SELC-4772] fix: Update workContract on userRegistry using an empty map

---

apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/model/UpdateUserRequest.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java

On POST /users/:id/user-registry endpoint:
* Avoid nullpointerexception checking id workContract is null
* Create object to update on PDV only if name/family/mail is really changed  and name/family is not SPID certified
* Refactor method improving readability 
nullpointerexception happens when user try to update an user without workContracts. In addition, an 409 error always occurs when user has name/family SPID value Certifiable.

[SELC-4777] hotfix: update user on pdv only when name/family/mail is changed

---

apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepositoryTest.java

* Create UserInfo only if valid product is present, otherwise it skip persisting UserInfo with institutions empty
* Fix adding institutions in case there are records UserInfo with institutions empty
* Unit tests more reliable
Issue occurs in production env on a UserInfo has institutions empty., new records with ACTIVE role have not beed added

[SELC-4881] fix: User CDC create UserInfo if there are valid product

---

apps/user-cdc/pom.xml
apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepositoryTest.java

* Implemented a validation step in the UserInfo creation process to check for existing institutions before adding a new one.
* Modified the logic to iterate over UserInstitution records and take only one the record that have a validation state and the higher role in terms of permission
This pull request addresses an issue in the **user-cdc** microservice where institutions could be duplicated when creating a UserInfo record. This duplication occurs if a UserInstitution record has more than one product in the **ACTIVE** state.

[SELC-4935] fix: Prevent Duplication of Institutions in UserInfo Creation

---

apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/SelfCareRole.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserPermissionController.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserPermissionService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserPermissionServiceImpl.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserPermissionControllerTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserPermissionServiceImplTest.java

- Refactor "/authorize" API to have institutionId as optional query param instead of required pathParam
We need to verify the permissions even when the only parameter for the verification is the productId.

[SELC-4970] Feat: Refactor "/authorize" API to have institutionId as optional query param

---

.github/labeler.yml
.github/workflows/pr_cdc.yml
.github/workflows/pr_container_apps__user_ms_infra.yml
.github/workflows/pr_ms.yml
.github/workflows/pr_user_group_ms.yml
.github/workflows/release_cdc.yml
.github/workflows/release_ms.yml
.github/workflows/release_pnpg_cdc.yml
.github/workflows/release_pnpg_ms.yml
.github/workflows/release_pnpg_user_group_ms.yml
.github/workflows/release_user_group_ms.yml
.github/workflows/release_user_sdk.yml

chore: added labeler for user-group-ms and rename workflow

---

apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserRegistryServiceImpl.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
apps/user-ms/src/main/resources/application.properties
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserRegistryServiceTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
infra/container_apps/user-ms/env/dev-pnpg/terraform.tfvars
infra/container_apps/user-ms/env/dev/terraform.tfvars
infra/container_apps/user-ms/env/prod-pnpg/terraform.tfvars
infra/container_apps/user-ms/env/prod/terraform.tfvars
infra/container_apps/user-ms/env/uat-pnpg/terraform.tfvars
infra/container_apps/user-ms/env/uat/terraform.tfvars

- Added retry in UserRegistry API
Sometimes UserRegistry returnes timeout so we have to use backoff retry for this case.

[SELC-4847] Feat: Added retry in UserRegistry API

---

apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/utils/CreateOrUpdateUserByFiscalCodeResponse.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/utils/OPERATION_TYPE.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/UserControllerTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java

* Updated the logic in the endpoint to check if an existing association is in the ACTIVE state.
* Modified the response to return a 200 status code instead of a 400 error if the association is already ACTIVE.
This pull request modifies the behavior of the endpoint that creates a new association between a user, product, and institution. Previously, if the association already existed in an ACTIVE state, the endpoint would return a 400 error. With this change, the endpoint will now return a 200 status code in such cases, indicating that the operation was successful and the association is already in an ACTIVE state.
The previous logic caused unnecessary errors when an onboarding try to persist an user already present with a product. By returning a 200 status code, we provide a more accurate …

[SELC-5193] feat: Modify Endpoint Response for Existing ACTIVE User-Institution Association

---

apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java

- modify method checkIfIsRetryableException to check if TooManyRequests exception is of type ClientWebApplicationException instead of WebApplicationException
This change is required to fix a missing retry during sendMessage to Event Hub
It was tested by running locally user-cdc and mocking user registry response with the help of Mockoon

[SELC-5266] fix: modify checkIfIsRetryableException to check if it's a ClientWebApplicationException

---

.github/workflows/swagger_detect_quarkus_ms.yml
apps/user-group-ms/app/src/main/docs/openapi.json
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserNotificationServiceImpl.java

Adding verification if workContracts is not null on retrievemail method
It causes NullPointerExeception when user has workContracts null.

hotfix: nullpointer when retrieve WorkContracts on retrievemail method

---

apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/mapper/NotificationMapper.java
apps/user-cdc/src/main/resources/application.properties
apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/mapper/NotificationMapperTest.java
apps/user-cdc/src/test/java/it/pagopa/selfcare/user/event/service/UserInstitutionCdcServiceTest.java
infra/container_apps/user-cdc/env/dev/terraform.tfvars
infra/container_apps/user-cdc/env/prod/terraform.tfvars
infra/container_apps/user-cdc/env/uat/terraform.tfvars
libs/user-sdk-event/pom.xml
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/UserUtils.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/auth/EventhubFdSasTokenAuthorization.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/client/EventHubFdRestClient.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/client/EventHubRestClient.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/FdUserNotificationToSend.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/NotificationUserType.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/TrackEventInput.java
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/UserToNotify.java
libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/FdUserNotificationToSendTest.java
libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/TrackEventInputTest.java
libs/user-sdk-event/src/test/java/it/pagopa/selfcare/user/UserUtilsTest.java
libs/user-sdk-model/src/main/java/it.pagopa.selfcare.user.model/constants/EventsMetric.java
libs/user-sdk-model/src/main/java/it.pagopa.selfcare.user.model/constants/EventsName.java

- Added send event for FD in user CDC only for product prod-fd and prod-fd-garantito
We have to send these events to FD when a new contract and a new user are created, and when an update is made to the user.

[SELC-5887] Feat: Added send event for FD in user CDC

---

apps/user-group-ms/connector-api/src/main/java/it/pagopa/selfcare/user_group/connector/exception/ResourceAlreadyExistsException.java
apps/user-group-ms/core/src/main/java/it/pagopa/selfcare/user_group/core/UserGroupServiceImpl.java
apps/user-group-ms/core/src/test/java/it/pagopa/selfcare/user_group/core/UserGroupServiceImplTest.java

added check of uniqueness group name in creation and editing api
To allow the existence of a group with the same name as a previously deleted group the unique index on the collection will be removed, and an application control will be added to inhibit the creation and modification of the group name if there are active or suspended groups with the same name.
local

[SELC-5956] feat: added check of uniqueness group name in creation and editing api

---

apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/UserInstitutionCdcService.java
apps/user-cdc/src/main/java/it/pagopa/selfcare/user/event/repository/UserInstitutionRepository.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java

*  change log level when user is not found
* using log built-in function instead of string.format
* remove update userInfo failded when an updated happens

chore: refactor some logs inside user-cdc and log level in ms when user not found

---

infra/container_apps/user-group-ms/env/uat-pnpg/terraform.tfvars
infra/container_apps/user-group-ms/mongo_db.tf
infra/container_apps/user-group-ms/variables.tf

* Added autoscale_settings vars to infra/**/user-groups 
* Set autoscale_settings in uat-pnpg vars
PNPG mongodb instance has an max_throughput equals 1000 but previous infra did not support setting this value.

ops: added autoscale_settings vars for MongoDB db

---

apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserResponse.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/UserMapper.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/mapper/UserMapperTest.java

- add mobilePhone field in retrieveUsers API response
- align mappers
- align unit tests
- align openapi

[SELC-6085] feat: add mobilePhone field in retrieveUsers API response

---

apps/user-ms/src/main/java/it/pagopa/selfcare/user/mapper/NotificationMapper.java

- modify toUserNotificationToSend mapper to retrieve mail from workContacts

hotfix: modify toUserNotificationToSend mapper to retrieve mail from workContacts

---

apps/pom.xml
apps/user-group-ms/pom.xml
apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/UserController.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/AddUserRoleDto.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/request/CreateUserDto.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/OnboardedProductResponse.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/UserInstitutionRoleResponse.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/product/OnboardedProductWithActions.java
apps/user-ms/src/main/resources/role_action_mapping.json
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/util/ActionMapRetrieverTest.java
apps/user-ms/src/test/resources/role_action_mapping_test.json
libs/user-sdk-event/src/main/java/it/pagopa/selfcare/user/model/UserToNotify.java
libs/user-sdk-model/pom.xml

Reverts pagopa/selfcare-user#245

Revert "[SELC-6300] feat: add role ADMIN_EA_IO"

---

apps/user-ms/src/main/docs/openapi.json
apps/user-ms/src/main/docs/openapi.yaml
apps/user-ms/src/main/java/it/pagopa/selfcare/user/constant/CustomError.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/InstitutionController.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/controller/response/DeletedUserCountResponse.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserInstitutionServiceDefault.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserService.java
apps/user-ms/src/main/java/it/pagopa/selfcare/user/service/UserServiceImpl.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/controller/InstitutionControllerTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserInstitutionServiceTest.java
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java

- Added new DELETE api /institutions/{institutionId}/products/{productId}/users to delete all the users in status ACTIVE or SUSPENDED associated to a product of an institution
The new api allow to delete all users related to no longer active onboardings
- Local tests
- Unit tests

[SELC-6726] Created new deleteUserInstitutionProductUsers API

---

.github/workflows/integration_tests_ms.yml
.github/workflows/integration_tests_user_group_ms.yml
apps/user-group-ms/src/test/java/it/pagopa/selfcare/user_group/integration_test/CucumberSuite.java

- Added workflow_dispatch
- Upload of cucumber.html test report
- Upload of report even if integration tests fail
Allows to start the integration tests manually and see the test results in a visually friendly output.
- Github Action Test

[SELC-7216] Allowing to manually start integration test workflow. Upload of the cucumber test report

---

apps/user-ms/src/main/resources/role_action_mapping.json
apps/user-ms/src/test/java/it/pagopa/selfcare/user/service/UserServiceTest.java
apps/user-ms/src/test/resources/features/user.feature

- Added new action ListProductGroups
- Removed action ManageProductGroups from ADMIN_EA role for prod-io
Added a new action which allows users to view only the groups they are a member of without modifying them: ADMIN_EA users for prod-io will not be able to manage groups.
- Local tests
- Unit tests
- Integration tests

[SELC-7480] Added new action ListProductGroups. Removed action ManageProductGroups from ADMIN_EA role for prod-io

---

apps/user-group-cdc/src/main/java/it/pagopa/selfcare/user/event/entity/UserGroupEntity.java
apps/user-group-ms/src/main/java/it/pagopa/selfcare/user_group/api/UserGroupOperations.java
apps/user-group-ms/src/main/java/it/pagopa/selfcare/user_group/model/GroupDto.java
apps/user-group-ms/src/main/java/it/pagopa/selfcare/user_group/model/UserGroupEntity.java
apps/user-group-ms/src/test/java/it/pagopa/selfcare/user_group/model/DummyGroup.java
apps/user-group-ms/src/test/resources/application-test.properties
apps/user-group-ms/src/test/resources/features/createGroup.feature

- add parentInstitutionId in UserGroups model
- set english as default cucumber tests' language
The parentInstitutionId field has been introduced to support the case of aggregator institutions. It allows us to identify when a user group is associated with an aggregator entity and to specify which aggregator it belongs to. This ensures clearer relationships between institutions and their respective groups.
Tested locally

[SELC-7461] feat: add parentInstitutionId in UserGroups model
